-- Migration 002: QR session tracking
-- Adds session_id + refresh_count to check_in_tokens so the server can:
--   1. Validate that only the originating device can auto-refresh a QR session.
--   2. Enforce a 3-refresh cap per session.
-- session_id is generated by the server on the first token of each session and
-- returned to the client; the client must present it on every refresh/invalidation.

ALTER TABLE check_in_tokens
  ADD COLUMN IF NOT EXISTS session_id    UUID NOT NULL DEFAULT gen_random_uuid(),
  ADD COLUMN IF NOT EXISTS refresh_count INT  NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_tokens_session ON check_in_tokens(session_id);
